"""
80 tennis evaluation questions for the portfolio-rag pipeline.

Each item has:
    id       — integer, stable across runs
    category — grouping tag for reporting
    input    — the user-facing question
    expected — ground-truth answer (used by the LLM-as-judge evaluator)
    articles — list of Wikipedia article titles that should be retrieved.
               Titles match fetch_corpus.py so the evaluator can sanitize
               them the same way to compare against chunk metadata.

Distribution:
    30  player_facts    (Big 3, current top, 2000s, historical, women)
    20  tournaments     (2020-2024 Grand Slams + ATP Finals)
    10  general         (tennis domain knowledge)
     8  comparative     (multi-article / H2H)
    12  follow_up       (6 pairs — tests conversational memory)
"""

test_questions = [
    # === PLAYER FACTS — BIG 3 (1-10) ===
    {"id": 1, "category": "player_facts",
     "input": "How many Grand Slam singles titles has Roger Federer won?",
     "expected": "20 Grand Slam singles titles",
     "articles": ["Roger Federer"]},
    {"id": 2, "category": "player_facts",
     "input": "How many Wimbledon singles titles has Roger Federer won?",
     "expected": "8 Wimbledon titles",
     "articles": ["Roger Federer"]},
    {"id": 3, "category": "player_facts",
     "input": "How many French Open singles titles has Rafael Nadal won?",
     "expected": "14 French Open titles",
     "articles": ["Rafael Nadal"]},
    {"id": 4, "category": "player_facts",
     "input": "How many total Grand Slam singles titles does Rafael Nadal have?",
     "expected": "22 Grand Slam singles titles",
     "articles": ["Rafael Nadal"]},
    {"id": 5, "category": "player_facts",
     "input": "How many Grand Slam singles titles has Novak Djokovic won?",
     "expected": "24 Grand Slam singles titles (record)",
     "articles": ["Novak Djokovic"]},
    {"id": 6, "category": "player_facts",
     "input": "How many Australian Open singles titles has Novak Djokovic won?",
     "expected": "10 Australian Open titles",
     "articles": ["Novak Djokovic"]},
    {"id": 7, "category": "player_facts",
     "input": "Which hand does Rafael Nadal play with?",
     "expected": "Left-handed",
     "articles": ["Rafael Nadal"]},
    {"id": 8, "category": "player_facts",
     "input": "What is Roger Federer's nationality?",
     "expected": "Swiss",
     "articles": ["Roger Federer"]},
    {"id": 9, "category": "player_facts",
     "input": "When did Roger Federer retire from professional tennis?",
     "expected": "September 2022, at the Laver Cup",
     "articles": ["Roger Federer"]},
    {"id": 10, "category": "player_facts",
     "input": "What is Novak Djokovic's nationality?",
     "expected": "Serbian",
     "articles": ["Novak Djokovic"]},

    # === PLAYER FACTS — CURRENT TOP (11-18) ===
    {"id": 11, "category": "player_facts",
     "input": "At which Grand Slam did Carlos Alcaraz win his first major title?",
     "expected": "2022 US Open",
     "articles": ["Carlos Alcaraz"]},
    {"id": 12, "category": "player_facts",
     "input": "At which Grand Slam did Jannik Sinner win his first major title?",
     "expected": "2024 Australian Open",
     "articles": ["Jannik Sinner"]},
    {"id": 13, "category": "player_facts",
     "input": "In what year did Daniil Medvedev win the US Open?",
     "expected": "2021",
     "articles": ["Daniil Medvedev"]},
    {"id": 14, "category": "player_facts",
     "input": "Which Grand Slam has Alexander Zverev reached the final of?",
     "expected": "US Open (2020) and French Open (2024)",
     "articles": ["Alexander Zverev"]},
    {"id": 15, "category": "player_facts",
     "input": "In what year did Stefanos Tsitsipas win the ATP Finals?",
     "expected": "2019",
     "articles": ["Stefanos Tsitsipas"]},
    {"id": 16, "category": "player_facts",
     "input": "Which surface is Casper Ruud best known for?",
     "expected": "Clay",
     "articles": ["Casper Ruud"]},
    {"id": 17, "category": "player_facts",
     "input": "What is Taylor Fritz's nationality?",
     "expected": "American",
     "articles": ["Taylor Fritz"]},
    {"id": 18, "category": "player_facts",
     "input": "In what year did Matteo Berrettini reach the Wimbledon final?",
     "expected": "2021",
     "articles": ["Matteo Berrettini"]},

    # === PLAYER FACTS — 2000s ERA (19-23) ===
    {"id": 19, "category": "player_facts",
     "input": "How many Grand Slam singles titles did Pete Sampras win?",
     "expected": "14 Grand Slam singles titles",
     "articles": ["Pete Sampras"]},
    {"id": 20, "category": "player_facts",
     "input": "Which player completed the Career Grand Slam and won an Olympic gold medal (Career Golden Slam)?",
     "expected": "Andre Agassi",
     "articles": ["Andre Agassi"]},
    {"id": 21, "category": "player_facts",
     "input": "In what year did Marat Safin win the Australian Open?",
     "expected": "2005",
     "articles": ["Marat Safin"]},
    {"id": 22, "category": "player_facts",
     "input": "Which was Andy Roddick's only Grand Slam singles title?",
     "expected": "2003 US Open",
     "articles": ["Andy Roddick"]},
    {"id": 23, "category": "player_facts",
     "input": "How many French Open titles did Gustavo Kuerten win?",
     "expected": "3 French Open titles (1997, 2000, 2001)",
     "articles": ["Gustavo Kuerten"]},

    # === PLAYER FACTS — HISTORICAL (24-27) ===
    {"id": 24, "category": "player_facts",
     "input": "Which player won the calendar-year Grand Slam twice?",
     "expected": "Rod Laver (1962 and 1969)",
     "articles": ["Rod Laver"]},
    {"id": 25, "category": "player_facts",
     "input": "How many Wimbledon singles titles did Björn Borg win?",
     "expected": "5 Wimbledon titles (1976-1980)",
     "articles": ["Björn Borg"]},
    {"id": 26, "category": "player_facts",
     "input": "Which player held the record for most consecutive weeks as world No. 1 before Federer?",
     "expected": "Jimmy Connors (160 consecutive weeks)",
     "articles": ["Jimmy Connors"]},
    {"id": 27, "category": "player_facts",
     "input": "Which historical player was famous for his serve-and-volley style and left-handed play?",
     "expected": "John McEnroe",
     "articles": ["John McEnroe"]},

    # === PLAYER FACTS — WOMEN (28-30) ===
    {"id": 28, "category": "player_facts",
     "input": "How many Grand Slam singles titles has Serena Williams won?",
     "expected": "23 Grand Slam singles titles",
     "articles": ["Serena Williams"]},
    {"id": 29, "category": "player_facts",
     "input": "Which player won the Golden Slam (all four majors plus Olympic gold) in a single calendar year?",
     "expected": "Steffi Graf (1988)",
     "articles": ["Steffi Graf"]},
    {"id": 30, "category": "player_facts",
     "input": "How many French Open titles has Iga Świątek won?",
     "expected": "4 French Open titles",
     "articles": ["Iga Świątek"]},

    # === TOURNAMENTS (31-50) ===
    {"id": 31, "category": "tournaments",
     "input": "Who won the 2020 Australian Open men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2020 Australian Open – Men's singles", "Novak Djokovic"]},
    {"id": 32, "category": "tournaments",
     "input": "Who won the 2020 US Open men's singles?",
     "expected": "Dominic Thiem",
     "articles": ["2020 US Open – Men's singles", "Dominic Thiem"]},
    {"id": 33, "category": "tournaments",
     "input": "Who won the 2021 French Open men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2021 French Open – Men's singles", "Novak Djokovic"]},
    {"id": 34, "category": "tournaments",
     "input": "Who won the 2021 Wimbledon men's singles final, and who was the runner-up?",
     "expected": "Novak Djokovic defeated Matteo Berrettini",
     "articles": ["2021 Wimbledon Championships – Men's singles",
                  "Novak Djokovic", "Matteo Berrettini"]},
    {"id": 35, "category": "tournaments",
     "input": "Who won the 2021 US Open men's singles?",
     "expected": "Daniil Medvedev (defeated Djokovic)",
     "articles": ["2021 US Open – Men's singles", "Daniil Medvedev"]},
    {"id": 36, "category": "tournaments",
     "input": "Who won the 2022 Australian Open men's singles?",
     "expected": "Rafael Nadal (defeated Medvedev in 5 sets)",
     "articles": ["2022 Australian Open – Men's singles", "Rafael Nadal"]},
    {"id": 37, "category": "tournaments",
     "input": "Who won the 2022 Wimbledon men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2022 Wimbledon Championships – Men's singles", "Novak Djokovic"]},
    {"id": 38, "category": "tournaments",
     "input": "Who won the 2022 US Open men's singles?",
     "expected": "Carlos Alcaraz",
     "articles": ["2022 US Open – Men's singles", "Carlos Alcaraz"]},
    {"id": 39, "category": "tournaments",
     "input": "Who won the 2023 Australian Open men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2023 Australian Open – Men's singles", "Novak Djokovic"]},
    {"id": 40, "category": "tournaments",
     "input": "Who won the 2023 French Open men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2023 French Open – Men's singles", "Novak Djokovic"]},
    {"id": 41, "category": "tournaments",
     "input": "Who won the 2023 Wimbledon men's singles final, and who was the runner-up?",
     "expected": "Carlos Alcaraz defeated Novak Djokovic",
     "articles": ["2023 Wimbledon Championships – Men's singles",
                  "Carlos Alcaraz", "Novak Djokovic"]},
    {"id": 42, "category": "tournaments",
     "input": "Who won the 2023 US Open men's singles?",
     "expected": "Novak Djokovic",
     "articles": ["2023 US Open – Men's singles", "Novak Djokovic"]},
    {"id": 43, "category": "tournaments",
     "input": "Who won the 2024 Australian Open men's singles?",
     "expected": "Jannik Sinner",
     "articles": ["2024 Australian Open – Men's singles", "Jannik Sinner"]},
    {"id": 44, "category": "tournaments",
     "input": "Who won the 2024 French Open men's singles?",
     "expected": "Carlos Alcaraz (defeated Zverev)",
     "articles": ["2024 French Open – Men's singles", "Carlos Alcaraz"]},
    {"id": 45, "category": "tournaments",
     "input": "Who won the 2024 Wimbledon men's singles?",
     "expected": "Carlos Alcaraz (defeated Djokovic)",
     "articles": ["2024 Wimbledon Championships – Men's singles", "Carlos Alcaraz"]},
    {"id": 46, "category": "tournaments",
     "input": "Who won the 2024 US Open men's singles?",
     "expected": "Jannik Sinner",
     "articles": ["2024 US Open – Men's singles", "Jannik Sinner"]},
    {"id": 47, "category": "tournaments",
     "input": "Who won the 2022 ATP Finals?",
     "expected": "Novak Djokovic",
     "articles": ["2022 ATP Finals", "Novak Djokovic"]},
    {"id": 48, "category": "tournaments",
     "input": "Who won the 2023 ATP Finals?",
     "expected": "Novak Djokovic",
     "articles": ["2023 ATP Finals", "Novak Djokovic"]},
    {"id": 49, "category": "tournaments",
     "input": "Who won the 2024 ATP Finals?",
     "expected": "Jannik Sinner",
     "articles": ["2024 ATP Finals", "Jannik Sinner"]},
    {"id": 50, "category": "tournaments",
     "input": "In what round of the 2022 Australian Open did Nadal face Medvedev?",
     "expected": "The final",
     "articles": ["2022 Australian Open – Men's singles"]},

    # === GENERAL TENNIS (51-60) ===
    {"id": 51, "category": "general",
     "input": "What are the four Grand Slam tournaments?",
     "expected": "Australian Open, French Open (Roland Garros), Wimbledon, US Open",
     "articles": ["Grand Slam (tennis)"]},
    {"id": 52, "category": "general",
     "input": "What is a Career Grand Slam in tennis?",
     "expected": "Winning all four Grand Slam tournaments at least once during a career",
     "articles": ["Career Grand Slam"]},
    {"id": 53, "category": "general",
     "input": "How does the ATP Finals tournament format work?",
     "expected": "Round-robin format with 8 qualified players split into two groups, followed by semifinals and final",
     "articles": ["ATP Finals"]},
    {"id": 54, "category": "general",
     "input": "What is the Davis Cup?",
     "expected": "International men's team tennis competition",
     "articles": ["Davis Cup"]},
    {"id": 55, "category": "general",
     "input": "What is the Laver Cup?",
     "expected": "Team tennis event between Team Europe and Team World, named after Rod Laver",
     "articles": ["Laver Cup"]},
    {"id": 56, "category": "general",
     "input": "When did the Open Era of tennis begin?",
     "expected": "1968",
     "articles": ["Open Era", "History of tennis"]},
    {"id": 57, "category": "general",
     "input": "How does scoring work in a tennis game (points)?",
     "expected": "15, 30, 40, game (with deuce/advantage at 40-40)",
     "articles": ["Tennis scoring system"]},
    {"id": 58, "category": "general",
     "input": "What surface is Roland Garros played on?",
     "expected": "Clay",
     "articles": ["Clay court", "French Open"]},
    {"id": 59, "category": "general",
     "input": "What surface is Wimbledon played on?",
     "expected": "Grass",
     "articles": ["Grass court"]},
    {"id": 60, "category": "general",
     "input": "What are the three main tennis court surfaces?",
     "expected": "Clay, grass, and hard court",
     "articles": ["Clay court", "Grass court", "Hard court", "Tennis court"]},

    # === COMPARATIVE (61-68) — multi-article retrieval ===
    {"id": 61, "category": "comparative",
     "input": "Who has more Grand Slam singles titles: Federer or Nadal?",
     "expected": "Nadal (22) has more than Federer (20)",
     "articles": ["Roger Federer", "Rafael Nadal"]},
    {"id": 62, "category": "comparative",
     "input": "Among the Big 3 (Federer, Nadal, Djokovic), who has won the most Australian Open titles?",
     "expected": "Novak Djokovic (10)",
     "articles": ["Novak Djokovic", "Roger Federer", "Rafael Nadal"]},
    {"id": 63, "category": "comparative",
     "input": "Who has won more Grand Slams, Pete Sampras or Roger Federer?",
     "expected": "Federer (20) has won more than Sampras (14)",
     "articles": ["Pete Sampras", "Roger Federer"]},
    {"id": 64, "category": "comparative",
     "input": "Between Alcaraz and Sinner, who won a Grand Slam first?",
     "expected": "Alcaraz (2022 US Open) won before Sinner (2024 Australian Open)",
     "articles": ["Carlos Alcaraz", "Jannik Sinner"]},
    {"id": 65, "category": "comparative",
     "input": "Has Djokovic ever lost a Wimbledon final to Alcaraz?",
     "expected": "Yes, in 2023 and 2024",
     "articles": ["Novak Djokovic", "Carlos Alcaraz",
                  "2023 Wimbledon Championships – Men's singles",
                  "2024 Wimbledon Championships – Men's singles"]},
    {"id": 66, "category": "comparative",
     "input": "Which of the Big 3 is left-handed?",
     "expected": "Rafael Nadal",
     "articles": ["Rafael Nadal", "Roger Federer", "Novak Djokovic"]},
    {"id": 67, "category": "comparative",
     "input": "Who has more Grand Slam singles titles, Serena Williams or Steffi Graf?",
     "expected": "Serena Williams (23) has one more than Graf (22)",
     "articles": ["Serena Williams", "Steffi Graf"]},
    {"id": 68, "category": "comparative",
     "input": "Which Big 3 player has won the most French Open titles?",
     "expected": "Rafael Nadal (14)",
     "articles": ["Rafael Nadal", "Novak Djokovic", "Roger Federer"]},

    # === FOLLOW-UP PAIRS (69-80) — q[i+1] depends on q[i] context ===
    {"id": 69, "category": "follow_up",
     "input": "How many Grand Slam titles has Novak Djokovic won?",
     "expected": "24 Grand Slam singles titles",
     "articles": ["Novak Djokovic"]},
    {"id": 70, "category": "follow_up",
     "input": "And how many of those were at the Australian Open?",
     "expected": "10 Australian Open titles",
     "articles": ["Novak Djokovic"]},

    {"id": 71, "category": "follow_up",
     "input": "Who won the 2022 US Open men's singles?",
     "expected": "Carlos Alcaraz",
     "articles": ["2022 US Open – Men's singles", "Carlos Alcaraz"]},
    {"id": 72, "category": "follow_up",
     "input": "How old was he when he won it?",
     "expected": "19 years old",
     "articles": ["Carlos Alcaraz"]},

    {"id": 73, "category": "follow_up",
     "input": "How many Wimbledon titles does Björn Borg have?",
     "expected": "5 (1976-1980)",
     "articles": ["Björn Borg"]},
    {"id": 74, "category": "follow_up",
     "input": "Who ended his streak there?",
     "expected": "John McEnroe (1981 Wimbledon final)",
     "articles": ["Björn Borg", "John McEnroe"]},

    {"id": 75, "category": "follow_up",
     "input": "Who won the 2023 Wimbledon men's final?",
     "expected": "Carlos Alcaraz defeated Novak Djokovic",
     "articles": ["2023 Wimbledon Championships – Men's singles",
                  "Carlos Alcaraz", "Novak Djokovic"]},
    {"id": 76, "category": "follow_up",
     "input": "How many sets did that match go?",
     "expected": "Five sets",
     "articles": ["2023 Wimbledon Championships – Men's singles"]},

    {"id": 77, "category": "follow_up",
     "input": "Who won the 2021 US Open men's singles?",
     "expected": "Daniil Medvedev",
     "articles": ["2021 US Open – Men's singles", "Daniil Medvedev"]},
    {"id": 78, "category": "follow_up",
     "input": "Who did he beat in the final?",
     "expected": "Novak Djokovic",
     "articles": ["2021 US Open – Men's singles",
                  "Daniil Medvedev", "Novak Djokovic"]},

    {"id": 79, "category": "follow_up",
     "input": "How many French Open titles does Rafael Nadal have?",
     "expected": "14",
     "articles": ["Rafael Nadal"]},
    {"id": 80, "category": "follow_up",
     "input": "In what year did he win his first one?",
     "expected": "2005",
     "articles": ["Rafael Nadal"]},
]


# Pairs where q[i+1] is a follow-up to q[i] (testing conversational memory).
follow_up_pairs = [
    (69, 70),   # Djokovic total GS -> how many at AO
    (71, 72),   # 2022 US Open winner -> how old was he
    (73, 74),   # Borg Wimbledon titles -> who ended streak
    (75, 76),   # 2023 Wimbledon final -> how many sets
    (77, 78),   # 2021 US Open winner -> beat who in final
    (79, 80),   # Nadal French titles -> first one year
]
